resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: Github_SolEng
      path: jfrogtraining/pipelines_swampup2020
      branches:
        include: training
  - name: myDockerAppImage
    type: Image
    configuration:
      registry: artifactory
      sourceRepository: team1-docker
      imageName: ${ArtIP}/team1-docker-dev-us/swampup_docker_app_demo
      imageTag: '${run_number}'
      autoPull: true
  - name: myOpenJDK11
    type: Image
    configuration:
      registry: artifactory
      sourceRepository: team1-docker
      imageName: ${ArtIP}/openjdk
      imageTag: '11-jdk'
      autoPull: true
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
      buildName: SampleApp
      buildNumber: 1

pipelines:
  - name: swampup_docker_app_pipeline
    configuration:
      environmentVariables:
        readOnly:
           my_env_var: '1.0.$run_number'
    steps:
      - name: bld_backend
        type: MvnBuild
        configuration:
          sourceLocation: java-backend-service
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: myGitRepo
              trigger: false
          integrations:
            - name: artifactory
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version
            - add_pipeline_variables previous_backend_ver=${my_env_var}
            - sed -ie 's/Default-Server/artifactory/g' $res_myGitRepo_resourcePath/java-backend-service/mvn-art-config
            - sed -ie "s/1.0.0/$my_env_var/g" $res_myGitRepo_resourcePath/java-backend-service/pom.xml
          onComplete:
            - echo $run_var
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"

      - name: bld_frontend
        type: NpmBuild
        configuration:
          npmArgs: --no-progress --no-audit
          sourceLocation: npm-frontend-service
          repositoryName: team1-npm
          inputResources:
            - name: myGitRepo
              trigger: false
          integrations:
            - name: artifactory
        execution:
          onStart:
            - add_pipeline_variables previous_frontend_ver=${my_env_var}
            - sed -i "s/3.0.0/$my_env_var/g" $res_myGitRepo_resourcePath/npm-frontend-service/package.json     
      - name: publish_frontend
        type: NpmPublish
        configuration:
          repositoryName: team1-npm
          inputSteps:
            - name: bld_frontend
          integrations:
            - name: artifactory

      - name: bld_docker_app
        type: DockerBuild
        configuration:
          affinityGroup: fmkGroup
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: '${ArtIP}/team1-docker-dev-us/swampup_docker_app_demo'
          dockerImageTag: '${run_number}'
          integrations:
            - name: artifactory
          inputResources:
            - name: myGitRepo
              trigger: false
          outputResources:
            - name: myDockerAppImage
          inputSteps:
            - name: bld_backend
            - name: publish_frontend #bld_frontend
        execution:
          onStart:
            - 'export ArtIP=$(echo ${int_artifactory_url}|awk -F ''/'' ''{print $3}'')'
            - sed -i "s/docker.artifactory/${ArtIP}\/artifactory/g" $res_myGitRepo_resourcePath/Dockerfile
            - sed -i "s/frontend-3.0.0/frontend-$previous_frontend_ver/g" $res_myGitRepo_resourcePath/Dockerfile
            - sed -i "s/1.0.0/$previous_backend_ver/g" $res_myGitRepo_resourcePath/Dockerfile
          onComplete:
            - echo $step_env_var2
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
      - name: push_docker_app
        type: DockerPush
        configuration:
          affinityGroup: fmkGroup
          targetRepository: team1-docker-dev-us
          forceXrayScan: false
          autoPublishBuildInfo: true
          integrations:
            - name: artifactory
          inputSteps:
            - name: bld_docker_app
          outputResources:
            - name: myBuildInfo
