resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: Github_SolEng
      path: jfrogtraining/pipelines_swampup2020
      branches:
        include: training

  - name: DockerAppImage
    type: Image
    configuration:
      registry: ArtifactoryUnified
      sourceRepository: docker
      imageName: docker.artifactory-unified-ha.soleng-us.jfrog.team/swampup_docker_app_demo
      imageTag: '${run_number}'
      autoPull: true

pipelines:
  - name: swampup_docker_app_pipeline
    configuration:
      environmentVariables:
        readOnly:
           my_env_var: '1.0.$run_number'
           ArtIP: $(echo ${int_ArtifactoryUnified_url}|awk -F '/' '{print $3}'|awk -F ':' '{print $1}')
